// Generated by CoffeeScript 1.4.0
(function() {

  $('.profile-bar').css({
    background: 'none',
    border: 'none'
  });

  $('.profile-bar .profile-holder, .profile-bar .stats').css({
    border: 'none'
  });

}).call(this);
