// Generated by CoffeeScript 1.3.3
(function() {
  var courses, day, field, fields, headers, _i, _len;

  window.log = function() {
    if (window.console) {
      return console.log.apply(console, arguments);
    }
  };

  courses = [];

  fields = ['startTime', 'className', 'trainerName', 'duration', 'location'];

  headers = {};

  day = null;

  for (_i = 0, _len = fields.length; _i < _len; _i++) {
    field = fields[_i];
    headers[field] = $("#" + field + "Header").index();
  }

  $("#classSchedule-mainTable tr").each(function() {
    var course, id, index, name;
    if ($(this).find("td.header").length > 0) {
      day = $(this).find("td.header").text().trim();
    }
    course = {};
    course.day = day;
    for (name in headers) {
      index = headers[name];
      if (!(index !== -1)) {
        continue;
      }
      course[name] = $(this).find("td:eq(" + index + ")").text().trim();
      if (name === 'trainerName') {
        id = $(this).find("td:eq(" + index + ") a").attr('name');
        if (id != null) {
          course.trainerId = id.replace("bio", "");
        }
      }
    }
    return courses.push(course);
  });

  log(courses.length);

  log(courses);

}).call(this);
