// Generated by CoffeeScript 1.3.3
(function() {
  var course, courses, day, field, fields, headers, _i, _j, _len, _len1;

  window.log = function() {
    if (window.console) {
      return console.log.apply(console, arguments);
    }
  };

  courses = [];

  fields = ['startTime', 'className', 'trainerName', 'duration', 'locationName'];

  headers = {};

  day = null;

  for (_i = 0, _len = fields.length; _i < _len; _i++) {
    field = fields[_i];
    headers[field] = $("#" + field + "Header").index();
  }

  $("#classSchedule-mainTable tr").each(function() {
    var course, id, index, name;
    if ($(this).find("td.header").length > 0) {
      day = $(this).find("td.header").text().trim();
    }
    course = {};
    course.day = day;
    course.location = document.title.replace(" Online", "");
    for (name in headers) {
      index = headers[name];
      if (!(index !== -1)) {
        continue;
      }
      course[name] = $(this).find("td:eq(" + index + ")").text().trim();
      switch (name) {
        case 'className':
          id = $(this).find("td:eq(" + index + ") a").attr('name');
          if (id != null) {
            course.classId = id.replace("cid", "");
          }
          break;
        case 'trainerName':
          id = $(this).find("td:eq(" + index + ") a").attr('name');
          if (id != null) {
            course.trainerId = id.replace("bio", "");
          }
          break;
        case 'locationName':
          if (course.locationName != null) {
            course.location += ": " + course.locationName;
            delete course.locationName;
          }
      }
    }
    return courses.push(course);
  });

  for (_j = 0, _len1 = courses.length; _j < _len1; _j++) {
    course = courses[_j];
    $.post("http://localhost:3000/import_mindbody", {
      course: course
    }, function(response) {
      return log(response);
    });
  }

}).call(this);
