// Generated by CoffeeScript 1.4.0
(function() {

  $('a.logo').html("<strong>heroku</strong>");

  $('.page-header').css({
    background: 'none',
    '-webkit-box-shadow': 'none'
  });

  $('.page-header .search input').css({
    'min-width': '80px',
    'font-size': '14px'
  });

  $('.hiring, .app-sorting').css({
    display: 'none'
  });

  $('.app-list .main-info hgroup').css({
    'padding-left': '5px'
  });

  $('.app-sorting ul li a[data-filter="stage:development"], .app-list .main-info hgroup').css({
    background: 'none'
  });

  $('.app-list .item.production hgroup, .stage-filter-is-hidden .app-list hgroup').css({
    background: 'none'
  });

}).call(this);
