// Generated by CoffeeScript 1.4.0
(function() {
  var b, bolds, centers, def, defs, div, f1, f2, f3, f4, footer, form, header_links, hr, hrs, i, link, links, logo, new_fields, old_fields, source, sources;

  logo = document.getElementsByTagName("center")[0];

  header_links = document.getElementsByTagName("p")[0];

  logo.parentNode.removeChild(logo);

  header_links.parentNode.removeChild(header_links);

  form = document.getElementsByTagName("form")[0];

  form.setAttribute("method", "get");

  f1 = document.getElementsByTagName("td")[1].innerHTML.replace("<br>", "");

  f2 = document.getElementsByTagName("td")[3].innerHTML.replace("<br>", "");

  f3 = document.getElementsByTagName("td")[5].innerHTML.replace("<br>", "");

  f4 = "<input type=\"submit\" value=\"Search\" name=\"submit\"/>";

  old_fields = document.getElementsByTagName("center")[1];

  old_fields.parentNode.removeChild(old_fields);

  new_fields = document.createElement("span");

  new_fields.innerHTML = f1 + f2 + f3 + f4;

  form.appendChild(new_fields);

  sources = document.getElementsByTagName("b");

  i = 0;

  while (i < sources.length) {
    source = sources[i];
    if (source.innerHTML.indexOf("From") === 0) {
      def = source.nextSibling;
      div = document.createElement("div");
      div.innerHTML = "<h2>" + source.innerHTML.replace("From ", "").replace(":", "") + "</h2>";
      div.style.width = "500px";
      div.style.borderLeft = "5px solid #DDDDDD";
      div.style.paddingLeft = "10px";
      div.style.marginRight = "20px";
      div.style.marginRight = "20px";
      div.style.cssFloat = "left";
      document.body.appendChild(div);
      div.appendChild(def);
    }
    i++;
  }

  defs = document.getElementsByTagName("pre");

  i = 0;

  while (i < defs.length) {
    def = defs[i];
    def.style.color = "#333333";
    def.style.fontSize = "11px";
    def.style.lineHeight = "16px";
    def.style.fontFamily = "'Lucida Grande', Verdana";
    i++;
  }

  sources = document.getElementsByTagName("h2");

  i = 0;

  while (i < sources.length) {
    source = sources[i];
    source.style.color = "#666666";
    source.style.fontSize = "16px";
    source.style.fontWeight = "normal";
    source.style.fontFamily = "Georgia, Sans";
    i++;
  }

  links = document.getElementsByTagName("a");

  i = 0;

  while (i < links.length) {
    link = links[i];
    link.style.color = "#0489B7";
    i++;
  }

  hrs = document.getElementsByTagName("hr");

  i = 0;

  while (i < hrs.length) {
    hr = hrs[i];
    hr.style.display = "none";
    i++;
  }

  centers = document.getElementsByTagName("center");

  footer = centers[centers.length - 1];

  footer.parentNode.removeChild(footer);

  bolds = document.getElementsByTagName("b");

  i = 0;

  while (i < bolds.length) {
    b = bolds[i];
    b.style.display = "none";
    i++;
  }

}).call(this);
