// Generated by CoffeeScript 1.3.3
(function() {
  var url, _s;

  $('#heroku-header, #heroku-subheader').css({
    display: 'none'
  });

  url = "https://s3.amazonaws.com/assets.heroku.com/hook/hook.js";

  _s = document.createElement('script');

  _s.src = url;

  _s.onload = function() {
    return console.log('onload');
  };

  document.getElementsByTagName('body')[0].appendChild(_s);

}).call(this);
